platform :ios, '8.0'

pod 'AFNetworking'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'
pod 'FMDB'
pod 'BlocksKit'
pod 'PureLayout'
pod 'JSPatch'
pod 'DZNEmptyDataSet'
pod 'MJRefresh'
pod 'FDFullscreenPopGesture'
pod 'UICKeyChainStore'
pod 'YYCache'
pod 'YYText'
pod 'UITableView+FDTemplateLayoutCell'
pod "MWPhotoBrowser"
pod 'MOBFoundation'
pod 'ShareSDK2'
pod 'ShareSDK2/Connection/WeChat'